# .air.toml
root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ./cmd/api/main.go"
bin = "./tmp/main"
delay = 100 # ms
exclude_dir = ["vendor", "tmp", "test", "docs"]
include_dir = ["cmd", "internal"]
include_ext = ["go"]
exclude_regex = ["_test\\.go"]
