// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package bootstrap

import (
	"github.com/gelozr/go-dash/internal/app"
	"github.com/gelozr/go-dash/internal/auth"
	"github.com/gelozr/go-dash/internal/config"
	"github.com/gelozr/go-dash/internal/customer"
	"github.com/gelozr/go-dash/internal/dashboard"
	"github.com/gelozr/go-dash/internal/db"
	"github.com/gelozr/go-dash/internal/event"
	"github.com/gelozr/go-dash/internal/event/bus"
	"github.com/gelozr/go-dash/internal/hashing"
	"github.com/gelozr/go-dash/internal/http"
	"github.com/gelozr/go-dash/internal/http/validation/gp"
	"github.com/gelozr/go-dash/internal/invoice"
	"github.com/gelozr/go-dash/internal/logger/slog"
	"github.com/gelozr/go-dash/internal/mail"
	"github.com/gelozr/go-dash/internal/user"
)

// Injectors from wire.go:

func InitApp() (*App, error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, err
	}
	logger, err := slog.New(configConfig)
	if err != nil {
		return nil, err
	}
	gormDB, err := db.Open(configConfig, logger)
	if err != nil {
		return nil, err
	}
	fiberServer := http.NewFiberServer(configConfig, logger)
	bootstrapTimezoneInitializer, err := setTimezone(configConfig)
	if err != nil {
		return nil, err
	}
	broker := event.NewBroker()
	gormStore := customer.NewStore(gormDB, logger)
	service := customer.NewService(gormStore, broker, logger)
	smtpMailer := mail.NewSMTPMailer(configConfig)
	manager := mail.NewManager(smtpMailer)
	registerInitializer := bus.RegisterAll(broker, service, manager, logger)
	gojwt := auth.NewGOJWT(configConfig)
	gormRefreshStore := auth.NewGormRefreshStore(gormDB, logger)
	token := auth.NewToken(gojwt, gormRefreshStore)
	userGormStore := user.NewStore(gormDB, logger)
	userService := user.NewService(userGormStore, logger)
	argon2IDHasher := hashing.NewArgon2IDHasher()
	hash := hashing.New(argon2IDHasher)
	passwordProvider := auth.NewPasswordProvider(userService, hash)
	googleProvider := auth.NewGoogleProvider()
	authManager := auth.NewManager(passwordProvider, googleProvider)
	authenticateUser := app.NewAuthenticateUser(authManager, token)
	authHandler := http.NewAuthHandler(authenticateUser)
	dashboardGormStore := dashboard.NewStore(gormDB, logger)
	dashboardService := dashboard.NewService(dashboardGormStore, logger)
	dashboardHandler := http.NewDashboardHandler(dashboardService, logger)
	userHandler := http.NewUserHandler(userService, logger)
	validator, err := gp.New()
	if err != nil {
		return nil, err
	}
	customerHandler := http.NewCustomerHandler(service, validator, logger)
	invoiceGormStore := invoice.NewStore(gormDB, logger)
	invoiceService := invoice.NewService(invoiceGormStore, logger)
	gormTxManager := db.NewTxManager(gormDB)
	createInvoice := app.NewCreateInvoice(service, invoiceService, gormTxManager, logger)
	invoiceHandler := http.NewInvoiceHandler(invoiceService, createInvoice, validator, logger)
	routeInitializer := http.SetupFiberRoutes(fiberServer, token, authHandler, dashboardHandler, userHandler, customerHandler, invoiceHandler)
	bootstrapApp := NewApp(configConfig, gormDB, logger, fiberServer, bootstrapTimezoneInitializer, registerInitializer, routeInitializer)
	return bootstrapApp, nil
}
